repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: |
          (?x)^(
          package.json
          )$
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
      - id: black
        exclude: |
          (?x)^(
          .*/migrations/.*
          )$
  - repo: https://github.com/pdm-project/pdm
    rev: 2.20.0
    hooks:
      - id: pdm-export
        args: ['-o', 'requirements.txt', '--without-hashes']
        files: ^pdm\.lock$
