# Generated by Django 5.0.3 on 2024-05-02 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='storage_quota',
            field=models.PositiveIntegerField(default=10485760),
        ),
    ]
