# Generated by Django 5.0.3 on 2024-05-09 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_storage_quota'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='back_image_rect',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='front_image_rect',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
