# Generated by Django 5.0.3 on 2024-06-28 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_userdiskquota_user_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdiskquota',
            old_name='storage_quota',
            new_name='value',
        ),
    ]
