# Generated by Django 5.0.3 on 2024-06-30 20:26

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_storage_quota_userdiskquota_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='army',
            name='private',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(upload_to=main.models.army_directory_path),
        ),
    ]
