# Generated by Django 5.0.3 on 2024-07-03 13:18

import functools
import main.models
import nanoid
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_army_private_alter_resource_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="table",
            name="id",
            field=main.models.NanoIdField(
                default=functools.partial(nanoid.generate, *(), **{"size": 12}),
                editable=False,
                max_length=12,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
