# Generated by Django 5.0.3 on 2024-07-08 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_table_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='boards/')),
                ('info', models.JSONField(default=dict)),
                ('defaultPriority', models.PositiveIntegerField(default=0, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='table',
            name='board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.board'),
        ),
    ]
