# Generated by Django 5.0.3 on 2024-07-25 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_emote'),
    ]

    operations = [
        migrations.AddField(
            model_name='army',
            name='readonly',
            field=models.BooleanField(default=False),
        ),
    ]
