# Generated by Django 5.0.3 on 2024-07-25 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_army_readonly'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replace_if_successful', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination', to='main.army')),
                ('source_army', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.army')),
            ],
        ),
    ]
