# Generated by Django 5.0.3 on 2024-08-01 15:12

import functools
import main.models
import nanoid
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_publicationrequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="army",
            name="id",
            field=main.models.NanoIdField(
                default=functools.partial(nanoid.generate, *(), **{"size": 12}),
                editable=False,
                max_length=12,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="board",
            name="id",
            field=main.models.NanoIdField(
                default=functools.partial(nanoid.generate, *(), **{"size": 12}),
                editable=False,
                max_length=12,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="chair",
            name="id",
            field=main.models.NanoIdField(
                default=functools.partial(nanoid.generate, *(), **{"size": 12}),
                editable=False,
                max_length=12,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="emote",
            name="id",
            field=main.models.NanoIdField(
                default=functools.partial(nanoid.generate, *(), **{"size": 12}),
                editable=False,
                max_length=12,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="link",
            name="id",
            field=main.models.NanoIdField(
                default=functools.partial(nanoid.generate, *(), **{"size": 12}),
                editable=False,
                max_length=12,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="namedinvitation",
            name="id",
            field=main.models.NanoIdField(
                default=functools.partial(nanoid.generate, *(), **{"size": 12}),
                editable=False,
                max_length=12,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="publicationrequest",
            name="id",
            field=main.models.NanoIdField(
                default=functools.partial(nanoid.generate, *(), **{"size": 12}),
                editable=False,
                max_length=12,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="id",
            field=main.models.NanoIdField(
                default=functools.partial(nanoid.generate, *(), **{"size": 12}),
                editable=False,
                max_length=12,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="token",
            name="id",
            field=main.models.NanoIdField(
                default=functools.partial(nanoid.generate, *(), **{"size": 12}),
                editable=False,
                max_length=12,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="userdiskquota",
            name="id",
            field=main.models.NanoIdField(
                default=functools.partial(nanoid.generate, *(), **{"size": 12}),
                editable=False,
                max_length=12,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
