# Generated by Django 5.0.3 on 2024-08-18 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_army_id_alter_board_id_alter_chair_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='army',
            name='utility',
            field=models.BooleanField(default=False),
        ),
    ]
