# Generated by Django 5.0.3 on 2024-08-29 18:05

import django.db.models.deletion
import functools
import main.models
import nanoid.generate
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_army_utility'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmoteAlternativeImage',
            fields=[
                ('id', main.models.NanoIdField(default=functools.partial(nanoid.generate, *(), **{'size': 12}), editable=False, max_length=12, primary_key=True, serialize=False, unique=True)),
                ('image', models.FileField(upload_to='emojis/')),
                ('emote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.emote')),
            ],
        ),
    ]
