# Generated by Django 5.0.3 on 2024-10-12 12:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_token_additional_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='multiplicity',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(35)]),
        ),
    ]
