# Generated by Django 5.0.3 on 2024-10-20 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_token_multiplicity'),
    ]

    operations = [
        migrations.AddField(
            model_name='army',
            name='keyshortcut',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
