# Generated by Django 5.0.3 on 2024-10-28 18:00

from django.db import migrations, models


def reorder(apps, schema_editor):
    MyModel = apps.get_model("main", "Link")
    for order, item in enumerate(MyModel.objects.all(), 1):
        item.my_order = order
        item.save(update_fields=["my_order"])


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0021_army_keyshortcut"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="link",
            options={"ordering": ["my_order"]},
        ),
        migrations.AddField(
            model_name="link",
            name="my_order",
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
        ),
        migrations.RunPython(reorder, reverse_code=migrations.RunPython.noop),
    ]
