# Generated by Django 5.0.3 on 2024-10-31 21:51

import functools
import main.models
import nanoid.generate
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_army_options_army_my_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', main.models.NanoIdField(default=functools.partial(nanoid.generate, *(), **{'size': 12}), editable=False, max_length=12, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=200)),
                ('my_order', models.PositiveSmallIntegerField(db_index=True, default=0)),
            ],
            options={
                'ordering': ['my_order'],
                'abstract': False,
            },
        ),
    ]
