const QUALITY_LEVELS = [
  { mouseUpdateCoolDown: -1, emotesCoolDown: [0, 0] },
  { mouseUpdateCoolDown: -1, emotesCoolDown: [1, 5000] },
  { mouseUpdateCoolDown: 500, emotesCoolDown: [3, 10000] },
  { mouseUpdateCoolDown: 250, emotesCoolDown: [9, 20000] },
  { mouseUpdateCoolDown: 150, emotesCoolDown: [20, 20000] },
  { mouseUpdateCoolDown: 100, emotesCoolDown: [20, 20000] },
];
const ADDITIONAL_QUALITY = 2;
export const SALT_ROUNDS = 7;
export const ENABLE_TIMEOUT = true;
export const CONNECTION_TIMEOUT = 20000;
export const PING_TIMEOUT = 5000;
export const STATS_SERVICE_INTERVAL = 5000;
export const QUALITY_LEVELS_NUM = QUALITY_LEVELS.length + ADDITIONAL_QUALITY - 1;
export const ADJUST_SERVICE_QUALITY = true;
export const INCREASE_QUALITY_THRESHOLD = 200;
export const DECREASE_QUALITY_THRESHOLD = 300;
export const DOUBLE_DECREASE_QUALITY_THRESHOLD = 500;
export const ADJUST_SERVICE_WS_CONNECTION_THRESHOLD = 8;
export const ADJUST_SERVICE_INCREASE_INSENSITIVITY = 2;
export const ADJUST_SERVICE_DECREASE_INSENSITIVITY = 3;
export const ARMY_SIZE_LIMIT = 1024 * 1024 * 2;
export { ADDITIONAL_QUALITY };
export { QUALITY_LEVELS };
export default {
  SALT_ROUNDS,
  ENABLE_TIMEOUT,
  CONNECTION_TIMEOUT,
  PING_TIMEOUT,
  STATS_SERVICE_INTERVAL,
  ADDITIONAL_QUALITY,
  QUALITY_LEVELS,
  QUALITY_LEVELS_NUM,
  ADJUST_SERVICE_QUALITY,
  INCREASE_QUALITY_THRESHOLD,
  DECREASE_QUALITY_THRESHOLD,
  DOUBLE_DECREASE_QUALITY_THRESHOLD,
  ADJUST_SERVICE_WS_CONNECTION_THRESHOLD,
  ADJUST_SERVICE_INCREASE_INSENSITIVITY,
  ADJUST_SERVICE_DECREASE_INSENSITIVITY,
  ARMY_SIZE_LIMIT
};
